-- ==========================================
-- 000: Budget dev tables
-- Purpose:
-- Documents the canonical DDL for the five core *_dev budget tables.
-- These were originally created manually in Supabase before migration
-- numbering was established (see docs/BUDGET_MIGRATION.md).
--
-- Run this only in a local/dev Supabase project to recreate the dev
-- schema from scratch.  For production tables, use 017 instead.
--
-- Subsequent migrations (016, 018, 019, 020, 021) ALTER these tables;
-- run them in order after this file when initializing a fresh dev environment.
-- ==========================================


-- ------------------------------------------
-- 1. budget_categories_dev
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS budget_categories_dev (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    category_name TEXT,
    sub_category_name TEXT,
    category_type TEXT,
    target_budget TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_personal BOOLEAN NOT NULL DEFAULT FALSE,
    username TEXT
);

CREATE INDEX IF NOT EXISTS idx_budget_categories_dev_household_active
    ON budget_categories_dev (household_id, is_active);

CREATE INDEX IF NOT EXISTS idx_budget_categories_dev_household_personal
    ON budget_categories_dev (household_id, is_personal, username);


-- ------------------------------------------
-- 2. household_incomes_dev
--    pay_frequency added by 016; payment_date by 018; source_expense_id by 020/021.
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS household_incomes_dev (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    month_year TEXT NOT NULL,
    source_name TEXT,
    take_home_amount TEXT,
    gross_amount TEXT,
    is_taxable BOOLEAN NOT NULL DEFAULT TRUE,
    owner_username TEXT,
    is_windfall BOOLEAN NOT NULL DEFAULT FALSE,
    is_recurring BOOLEAN NOT NULL DEFAULT FALSE,
    is_personal_income BOOLEAN NOT NULL DEFAULT FALSE,
    payment_date DATE,
    pay_frequency TEXT DEFAULT 'monthly',
    source_expense_id TEXT
);

CREATE INDEX IF NOT EXISTS idx_household_incomes_dev_household_month
    ON household_incomes_dev (household_id, month_year);

CREATE INDEX IF NOT EXISTS idx_household_incomes_dev_household_personal
    ON household_incomes_dev (household_id, month_year, is_personal_income, owner_username);


-- ------------------------------------------
-- 3. expenses_dev
--    Note: id is UUID in the live dev Supabase DB (historical default).
--    BIGINT is used here for new installs; the audit script will flag
--    the existing dev DB id type as an expected mismatch.
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS expenses_dev (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    auth_user_id TEXT,
    username TEXT,
    month_year TEXT NOT NULL,
    date_logged DATE,
    category_id BIGINT REFERENCES budget_categories_dev (id) ON DELETE SET NULL,
    amount TEXT,
    details TEXT,
    is_personal_spend BOOLEAN NOT NULL DEFAULT FALSE,
    is_recurring BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_expenses_dev_household_month
    ON expenses_dev (household_id, month_year);

CREATE INDEX IF NOT EXISTS idx_expenses_dev_household_user_month
    ON expenses_dev (household_id, auth_user_id, month_year);

CREATE INDEX IF NOT EXISTS idx_expenses_dev_category
    ON expenses_dev (category_id);


-- ------------------------------------------
-- 4. cash_flow_routing_dev
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS cash_flow_routing_dev (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    destination_account TEXT,
    line_item TEXT,
    annual_goal TEXT,
    monthly_target TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_cash_flow_routing_dev_household_active
    ON cash_flow_routing_dev (household_id, is_active);


-- ------------------------------------------
-- 5. user_finance_settings_dev
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS user_finance_settings_dev (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    username TEXT NOT NULL,
    share_budget_with_admin BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_user_finance_settings_dev_household_username
        UNIQUE (household_id, username)
);

CREATE INDEX IF NOT EXISTS idx_user_finance_settings_dev_household
    ON user_finance_settings_dev (household_id);

NOTIFY pgrst, 'reload schema';
