-- ==========================================
-- 010: Wish List tables (prod + local/dev)
-- Purpose:
-- Add a simple household-scoped wish list module with role-aware row ownership.
-- ==========================================

CREATE TABLE IF NOT EXISTS wish_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    owner_auth_user_id TEXT,
    owner_username TEXT,
    item TEXT NOT NULL,
    description TEXT,
    estimated_price NUMERIC,
    actual_cost NUMERIC,
    veteran_discount BOOLEAN NOT NULL DEFAULT FALSE,
    vendor TEXT,
    notes TEXT,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wish_list_household_created
    ON wish_list (household_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_wish_list_household_updated
    ON wish_list (household_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS wish_list_dev (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    owner_auth_user_id TEXT,
    owner_username TEXT,
    item TEXT NOT NULL,
    description TEXT,
    estimated_price NUMERIC,
    actual_cost NUMERIC,
    veteran_discount BOOLEAN NOT NULL DEFAULT FALSE,
    vendor TEXT,
    notes TEXT,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wish_list_dev_household_created
    ON wish_list_dev (household_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_wish_list_dev_household_updated
    ON wish_list_dev (household_id, updated_at DESC);
