-- ==========================================
-- 017: Monthly budget production tables
-- Purpose:
-- Create the five core prod tables used by the budget module when
-- app_config.environment != "local".
--
-- Run this BEFORE migrations/016_add_income_pay_frequency.sql
-- (016 adds pay_frequency to household_incomes; run 017 first, then 016).
-- ==========================================

-- ------------------------------------------
-- 1. budget_categories
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS budget_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    category_name TEXT,
    sub_category_name TEXT,
    category_type TEXT,
    target_budget TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_personal BOOLEAN NOT NULL DEFAULT FALSE,
    username TEXT
);

CREATE INDEX IF NOT EXISTS idx_budget_categories_household_active
    ON budget_categories (household_id, is_active);

CREATE INDEX IF NOT EXISTS idx_budget_categories_household_personal
    ON budget_categories (household_id, is_personal, username);

-- ------------------------------------------
-- 2. household_incomes
-- pay_frequency is added in migration 016
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS household_incomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    month_year TEXT NOT NULL,
    source_name TEXT,
    take_home_amount TEXT,
    gross_amount TEXT,
    is_taxable BOOLEAN NOT NULL DEFAULT TRUE,
    owner_username TEXT,
    is_windfall BOOLEAN NOT NULL DEFAULT FALSE,
    is_recurring BOOLEAN NOT NULL DEFAULT FALSE,
    is_personal_income BOOLEAN NOT NULL DEFAULT FALSE,
    payment_date DATE
);

CREATE INDEX IF NOT EXISTS idx_household_incomes_household_month
    ON household_incomes (household_id, month_year);

CREATE INDEX IF NOT EXISTS idx_household_incomes_household_personal
    ON household_incomes (household_id, month_year, is_personal_income, owner_username);

-- ------------------------------------------
-- 3. expenses
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    auth_user_id TEXT,
    username TEXT,
    month_year TEXT NOT NULL,
    date_logged DATE,
    category_id BIGINT REFERENCES budget_categories (id) ON DELETE SET NULL,
    amount TEXT,
    details TEXT,
    is_personal_spend BOOLEAN NOT NULL DEFAULT FALSE,
    is_recurring BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_expenses_household_month
    ON expenses (household_id, month_year);

CREATE INDEX IF NOT EXISTS idx_expenses_household_user_month
    ON expenses (household_id, auth_user_id, month_year);

CREATE INDEX IF NOT EXISTS idx_expenses_category
    ON expenses (category_id);

-- ------------------------------------------
-- 4. cash_flow_routing
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS cash_flow_routing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    destination_account TEXT,
    line_item TEXT,
    annual_goal TEXT,
    monthly_target TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_cash_flow_routing_household_active
    ON cash_flow_routing (household_id, is_active);

-- ------------------------------------------
-- 5. user_finance_settings
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS user_finance_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    username TEXT NOT NULL,
    share_budget_with_admin BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_user_finance_settings_household_username
        UNIQUE (household_id, username)
);

CREATE INDEX IF NOT EXISTS idx_user_finance_settings_household
    ON user_finance_settings (household_id);

NOTIFY pgrst, 'reload schema';
