-- ==========================================
-- 022: Prod / dev schema parity catch-all
-- Purpose:
-- Idempotent migration that brings every production table up to parity
-- with its *_dev counterpart.  Safe to run multiple times.
-- Run this after the audit (maintenance/audit_schema_parity.py) reports gaps.
--
-- Section order matches the table creation order in 017.
-- ==========================================


-- ------------------------------------------
-- 1. budget_categories
--    Base columns created by 017.
--    No additional columns were added to _dev since 017.
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS budget_categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    category_name TEXT,
    sub_category_name TEXT,
    category_type TEXT,
    target_budget TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_personal BOOLEAN NOT NULL DEFAULT FALSE,
    username TEXT
);

CREATE INDEX IF NOT EXISTS idx_budget_categories_household_active
    ON budget_categories (household_id, is_active);

CREATE INDEX IF NOT EXISTS idx_budget_categories_household_personal
    ON budget_categories (household_id, is_personal, username);

ALTER TABLE budget_categories
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE budget_categories
    ADD COLUMN IF NOT EXISTS is_annual BOOLEAN NOT NULL DEFAULT FALSE;


-- ------------------------------------------
-- 2. household_incomes
--    Base from 017; 016 adds pay_frequency; 018 adds payment_date (already
--    in 017 CREATE but 016 must still set DEFAULT and backfill);
--    020 adds source_expense_id; 021 ensures TEXT type.
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS household_incomes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    month_year TEXT NOT NULL,
    source_name TEXT,
    take_home_amount TEXT,
    gross_amount TEXT,
    is_taxable BOOLEAN NOT NULL DEFAULT TRUE,
    owner_username TEXT,
    is_windfall BOOLEAN NOT NULL DEFAULT FALSE,
    is_recurring BOOLEAN NOT NULL DEFAULT FALSE,
    is_personal_income BOOLEAN NOT NULL DEFAULT FALSE,
    payment_date DATE
);

CREATE INDEX IF NOT EXISTS idx_household_incomes_household_month
    ON household_incomes (household_id, month_year);

CREATE INDEX IF NOT EXISTS idx_household_incomes_household_personal
    ON household_incomes (household_id, month_year, is_personal_income, owner_username);

-- pay_frequency (migration 016)
ALTER TABLE household_incomes
    ADD COLUMN IF NOT EXISTS pay_frequency TEXT;

UPDATE household_incomes
SET pay_frequency = CASE
    WHEN COALESCE(is_recurring, FALSE) THEN 'monthly'
    ELSE 'one_time'
END
WHERE pay_frequency IS NULL OR pay_frequency = '';

ALTER TABLE household_incomes
    ALTER COLUMN pay_frequency SET DEFAULT 'monthly';

-- payment_date already in 017 CREATE; ensure it exists for partial deployments
ALTER TABLE household_incomes
    ADD COLUMN IF NOT EXISTS payment_date DATE;

UPDATE household_incomes
SET payment_date = (month_year || '-01')::DATE
WHERE payment_date IS NULL;

-- source_expense_id (migration 020 + 021)
ALTER TABLE household_incomes
    ADD COLUMN IF NOT EXISTS source_expense_id TEXT;

ALTER TABLE household_incomes
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();


-- ------------------------------------------
-- 3. expenses
--    Base from 017.  No additional columns beyond 017.
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS expenses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    auth_user_id TEXT,
    username TEXT,
    month_year TEXT NOT NULL,
    date_logged DATE,
    category_id BIGINT REFERENCES budget_categories (id) ON DELETE SET NULL,
    amount TEXT,
    details TEXT,
    is_personal_spend BOOLEAN NOT NULL DEFAULT FALSE,
    is_recurring BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_expenses_household_month
    ON expenses (household_id, month_year);

CREATE INDEX IF NOT EXISTS idx_expenses_household_user_month
    ON expenses (household_id, auth_user_id, month_year);

CREATE INDEX IF NOT EXISTS idx_expenses_category
    ON expenses (category_id);

ALTER TABLE expenses
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();


-- ------------------------------------------
-- 4. cash_flow_routing
--    Base from 017.
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS cash_flow_routing (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    destination_account TEXT,
    line_item TEXT,
    annual_goal TEXT,
    monthly_target TEXT,
    is_active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE INDEX IF NOT EXISTS idx_cash_flow_routing_household_active
    ON cash_flow_routing (household_id, is_active);

ALTER TABLE cash_flow_routing
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();

ALTER TABLE cash_flow_routing
    ADD COLUMN IF NOT EXISTS is_recurring BOOLEAN NOT NULL DEFAULT FALSE;


-- ------------------------------------------
-- 5. user_finance_settings
--    Base from 017.
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS user_finance_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    username TEXT NOT NULL,
    share_budget_with_admin BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_user_finance_settings_household_username
        UNIQUE (household_id, username)
);

CREATE INDEX IF NOT EXISTS idx_user_finance_settings_household
    ON user_finance_settings (household_id);

ALTER TABLE user_finance_settings
    ADD COLUMN IF NOT EXISTS personal_savings_goal TEXT;

ALTER TABLE user_finance_settings
    ADD COLUMN IF NOT EXISTS default_view TEXT DEFAULT 'Household';

ALTER TABLE user_finance_settings
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ DEFAULT NOW();


-- ------------------------------------------
-- 6. household_tasks
--    Base table predates migrations (created before migration numbering).
--    Migration 005 adds description, notes, is_recurring, recurrence_pattern.
-- ------------------------------------------
ALTER TABLE household_tasks
    ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE household_tasks
    ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE household_tasks
    ADD COLUMN IF NOT EXISTS is_recurring BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE household_tasks
    ADD COLUMN IF NOT EXISTS recurrence_pattern TEXT;

CREATE INDEX IF NOT EXISTS idx_household_tasks_household_due
    ON household_tasks (household_id, is_completed, target_date);


-- ------------------------------------------
-- 7. project_budgets
--    Base table predates migration numbering.
--    Migration 007 drops numeric defaults (already a no-op if defaults absent).
--    Fields: item, description, est_low_cost, est_high_cost, actual_cost,
--            vendors, notes, priority, status, household_id, is_completed.
-- ------------------------------------------
ALTER TABLE project_budgets
    ALTER COLUMN est_low_cost DROP DEFAULT;

ALTER TABLE project_budgets
    ALTER COLUMN est_high_cost DROP DEFAULT;

ALTER TABLE project_budgets
    ALTER COLUMN actual_cost DROP DEFAULT;

-- Ensure commonly referenced columns exist (idempotent)
ALTER TABLE project_budgets
    ADD COLUMN IF NOT EXISTS description TEXT;

ALTER TABLE project_budgets
    ADD COLUMN IF NOT EXISTS vendors TEXT;

ALTER TABLE project_budgets
    ADD COLUMN IF NOT EXISTS notes TEXT;

ALTER TABLE project_budgets
    ADD COLUMN IF NOT EXISTS priority INTEGER;

ALTER TABLE project_budgets
    ADD COLUMN IF NOT EXISTS status TEXT;

ALTER TABLE project_budgets
    ADD COLUMN IF NOT EXISTS is_completed BOOLEAN;


-- ------------------------------------------
-- 8. household_finance_settings
--    Base from 006.  Migration 008 adds projects_funds_year.
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS household_finance_settings (
    household_id TEXT PRIMARY KEY,
    projects_funds NUMERIC,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_household_finance_settings_updated_at
    ON household_finance_settings (updated_at DESC);

-- projects_funds_year (migration 008)
ALTER TABLE household_finance_settings
    ADD COLUMN IF NOT EXISTS projects_funds_year INTEGER;


-- ------------------------------------------
-- 9. wish_list
--    Base from 010.  Migration 011 adds owner_auth_user_id / owner_username.
--    Migration 013 adds is_completed (already in 010 CREATE; safe to re-add).
-- ------------------------------------------
CREATE TABLE IF NOT EXISTS wish_list (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    household_id TEXT NOT NULL,
    owner_auth_user_id TEXT,
    owner_username TEXT,
    item TEXT NOT NULL,
    description TEXT,
    estimated_price NUMERIC,
    actual_cost NUMERIC,
    veteran_discount BOOLEAN NOT NULL DEFAULT FALSE,
    vendor TEXT,
    notes TEXT,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_wish_list_household_created
    ON wish_list (household_id, created_at DESC);

CREATE INDEX IF NOT EXISTS idx_wish_list_household_updated
    ON wish_list (household_id, updated_at DESC);

-- Ensure owner columns exist for pre-010 installs (migration 011)
ALTER TABLE wish_list
    ADD COLUMN IF NOT EXISTS owner_auth_user_id TEXT;

ALTER TABLE wish_list
    ADD COLUMN IF NOT EXISTS owner_username TEXT;

-- Ensure is_completed exists and is non-nullable (migration 013)
ALTER TABLE wish_list
    ADD COLUMN IF NOT EXISTS is_completed BOOLEAN;

UPDATE wish_list
SET is_completed = COALESCE(is_completed, FALSE);

ALTER TABLE wish_list
    ALTER COLUMN is_completed SET DEFAULT FALSE;

ALTER TABLE wish_list
    ALTER COLUMN is_completed SET NOT NULL;


-- ------------------------------------------
-- Notify PostgREST to reload the schema cache
-- ------------------------------------------
NOTIFY pgrst, 'reload schema';
